#ifndef __MESSAGE_HEADER__
#define __MESSAGE_HEADER__

#define APPLY_DOMAIN "/tmp/apply.domain"

#define LKTOS_DOMAIN "/tmp/lktos.domain" 

#define MAX_MSG_SIZE 1024

typedef unsigned int MsgType;

#define APPLY_MSG_PAYLOAD_OFFSET                       65550

typedef enum
{
	APPLY_MSG_RELOAD_NETWORK = APPLY_MSG_PAYLOAD_OFFSET,
	APPLY_MSG_RELOAD_WAN_PORT_DOWN,
	APPLY_MSG_RELOAD_WAN_PORT_UP, 
	APPLY_MSG_RELOAD_WANDOWN,
	APPLY_MSG_RELOAD_WANUP,
	APPLY_MSG_RELOAD_LANUP,
	APPLY_MSG_RELOAD_LAN,
	APPLY_MSG_RELOAD_WIRELESS,
	APPLY_MSG_RELOAD_ACL,
	APPLY_MSG_RELOAD_DHCP,
	APPLY_MSG_RELOAD_PPTPD,
	APPLY_MSG_RELOAD_L2TPD,
	APPLY_MSG_RELOAD_PPPUSER,
	APPLY_MSG_RELOAD_OPENVPND,
	APPLY_MSG_RELOAD_OPENVPNC,
	APPLY_MSG_RELOAD_OPENVPNC_FW,
	APPLY_MSG_RELOAD_DDNS,
	APPLY_MSG_RELOAD_UDHCPD,
	APPLY_MSG_RELOAD_PPPOE_CONNECT,
	APPLY_MSG_RELOAD_PPPOE_DISCONNECT,
	APPLY_MSG_RELOAD_INIT_FW,
	APPLY_MSG_RELOAD_IP_PORT_FILTER,
	APPLY_MSG_RELOAD_MAC_FIlTER,
	APPLY_MSG_RELOAD_WEB_FIlTER,
	APPLY_MSG_RELOAD_PORT_FORWARD,
	APPLY_MSG_RELOAD_VPN_PASS_THROUGH,
	APPLY_MSG_RELOAD_DMZ,
	APPLY_MSG_RELOAD_DOS,
	APPLY_MSG_RELOAD_SCHEDULE,
	APPLY_MSG_RELOAD_REMOTE_MANAGEMENT,
	APPLY_MSG_RELOAD_L7_FIlTER,
	APPLY_MSG_RELOAD_CONN_LIMIT,
	APPLY_MSG_RELOAD_CRPC,
	APPLY_MSG_RELOAD_SS_SERVER,
	APPLY_MSG_RELOAD_IPSEC,
	APPLY_MSG_RELOAD_IPSEC_FW,
	APPLY_MSG_LOAD_DEF_SETTINGS,
	APPLY_MSG_UPLOAD_SETTINGS,
	APPLY_MSG_FW_UPGRADE,
	APPLY_MSG_FW_AUTO_UPGRADE,
	APPLY_MSG_RELOAD_TELNET,
	APPLY_MSG_CLOUD_UPGRADE_CHECK,
	APPLY_MSG_RELOAD_STATIC_ROUTE,
	APPLY_MSG_RELOAD_PORTALOS,
	APPLY_MSG_RELOAD_WIFIDOG,
	APPLY_MSG_CREAT_OPENVPND_CERT,
	APPLY_MSG_HW_NAT,
	APPLY_MSG_RELOAD_SYSTEM,
	APPLY_MSG_RELOAD_INIT_IGMPPROXY,
	APPLY_MSG_RELOAD_PARENTAL_FIlTER,
	APPLY_MSG_RELOAD_SAMBA_SERVER,
	APPLY_MSG_RELOAD_DLNA_SERVER,
	APPLY_MSG_RELOAD_FTP_SERVER,
	APPLY_MSG_RELOAD_WPS,
	APPLY_MSG_RELOAD_ACCESSLIST,
	APPLY_MSG_RELOAD_UPNPD,
	APPLY_MSG_START_MESH,
	APPLY_MSG_RESET_TO_DEFAULT_MESH,
	APPLY_MSG_RELOAD_MESH,
	APPLY_MSG_RELOAD_SMARTQOS,
	APPLY_MSG_RELOAD_WLANQOS,
	APPLY_MSG_RELOAD_QUAGGA,
	APPLY_MSG_RELOAD_DYNAMIC,
	APPLY_MSG_RELOAD_GUESTWIFI,
	APPLY_MSG_DELAY_REBOOT,
	APPLY_MSG_SCAN_WIFI,
	APPLY_MSG_RELOAD_NTP,
#if defined(CONFIG_USER_NETCWMP)
	APPLY_MSG_RELOAD_STUN,
#endif
#if defined(CONFIG_ANDLINK_SUPPORT)
	APPLY_MSG_RELOAD_ANDLINK,
	APPLY_MSG_RELOAD_LOCKNET,
#endif //#if defined(CONFIG_ANDLINK_SUPPORT)
	APPLY_MSG_RELOAD_CWMPFIREWALL,
	
	APPLY_MSG_RELOAD_MAX,
}APPLY_MSG_DEF;


#define APPLY_FUNC_SIZE      (APPLY_MSG_RELOAD_MAX-APPLY_MSG_PAYLOAD_OFFSET) 

#endif /* __MESSAGE_HEADER__ */

